version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  api:
    build:
      context: .
    environment:
      PORT: 4000
      JWT_KEY: 123
      JWT_EXPIRATION: 1h
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./src/:/usr/src/app